### ISSUE TITLE
请教您一个国密证书配置的问题

### ISSUE THREAD

**Issue by tmaccs** [kings-way/pki_in_shell#1]
我编译apache httpd的时候设置了--with-ssl=/usr/local/gmssl
试用Gmssl生成的server.key和server.crt， httpd能够正常启动，但是使用密信浏览器访问这个服务器的时候，一直显示：

此网站无法提供安全连接
10.22.2.112 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

我的ssl.conf配置:
Listen 443
<VirtualHost *:443>
        ServerName localhost 
        DocumentRoot "/var/www/web_console"
        ErrorLog logs/ssl_error_log
        TransferLog logs/ssl_access_log
        LogLevel warn
        SSLEngine on
        SSLCertificateFile /usr/local/httpd/conf/10.22.2.112.crt
        SSLCertificateKeyFile /usr/local/httpd/conf/10.22.2.112.key
        #sign 和 encrypt 配置中的.key 和 bundle.crt 为同一个
        SSLProtocol all -SSLv2 -SSLv3 
        #SSLCipherSuite EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:SM2-WITH-SMS4-SM3:ECDH:AESGCM:HIGH:!RC4:!DH:!MD5:!aNULL:!eNULL
        SSLCipherSuite ECDHE-SM2-WITH-SMS4-GCM-SM3:SM2-WITH-SMS4-SM3:ECDH:AESGCM:HIGH:!RC4:!DH:!MD5:!aNULL:!eNULL
        #SSLCipherSuite ECDHE-SM4-SM3:SM2-WITH-SMS4-SM3:ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!3DES:!MD5:!ADH:!RC4:!DH:!DHE
        SSLHonorCipherOrder on
        <Directory "/var/www/web_console">
                Options -Indexes -FollowSymLinks +ExecCGI
                AllowOverride None
                Order allow,deny
                Allow from all
                Require all granted
        </Directory>
</VirtualHost>

您有遇到过这个问题吗？
谢谢！

**Comment by kings-way** [comment]
我好久没玩过apache了，不过建议你用 openssl / gmssl 命令行排查问题，如下：

    openssl s_client -connect  www.example.com:443
